import { describe, it, expect, vi, beforeEach } from 'vitest';
import * as fc from 'fast-check';
import { ReportPipelineOrchestrator, ChapterResult } from '../../src/pipeline/orchestrator';
import { ChapterDataLoaderRegistry } from '../../src/pipeline/loaders/types';
import { PromptTemplateLoader } from '../../src/pipeline/template-loader';
import type { LLMClient } from '../../src/report/llm-client';

/**
 * Property 4: Pipeline resilience on LLM failure
 * Validates: Requirements 4.5
 *
 * For any chapter index N (2-9) where the LLM call fails or times out,
 * the pipeline SHALL still produce a complete 10-chapter report where
 * chapter N has status: 'error' with fallback content, and all other
 * chapters have their independently generated content unaffected.
 */
describe('Feature: report-generation-pipeline, Property 4: Pipeline resilience on LLM failure', () => {
  // Chapter metadata for all 10 chapters
  const chapterMetadata: Array<{ number: number; name: string; fallback: string }> = [
    { number: 1, name: '封面', fallback: '封面内容生成失败，请重试。' },
    { number: 2, name: '项目回顾', fallback: '项目回顾内容生成失败，请重试。' },
    { number: 3, name: '数据总览', fallback: '数据总览内容生成失败，请重试。' },
    { number: 4, name: '项目亮点', fallback: '项目亮点内容生成失败，请重试。' },
    { number: 5, name: '综合分析', fallback: '综合分析内容生成失败，请重试。' },
    { number: 6, name: '内容分析', fallback: '内容分析内容生成失败，请重试。' },
    { number: 7, name: '投流分析', fallback: '投流分析内容生成失败，请重试。' },
    { number: 8, name: '人群资产', fallback: '人群资产内容生成失败，请重试。' },
    { number: 9, name: '优化建议', fallback: '优化建议内容生成失败，请重试。' },
    { number: 10, name: '尾页', fallback: '尾页内容生成失败，请重试。' },
  ];

  // Mock template loader
  function createMockTemplateLoader(): PromptTemplateLoader {
    const loader = {
      loadTemplate: vi.fn((chapterNumber: number) => {
        const meta = chapterMetadata[chapterNumber - 1];
        return {
          metadata: {
            chapter_number: chapterNumber,
            chapter_name: meta.name,
            required_data_sources: ['projects'],
            output_format: 'paragraphs' as const,
            fallback_text: meta.fallback,
          },
          systemPrompt: chapterNumber === 1 || chapterNumber === 10 ? '' : 'You are an expert.',
          userPromptTemplate: `Chapter ${chapterNumber} content template`,
        };
      }),
      substituteVariables: vi.fn((_template: string, _variables: Record<string, string>) => {
        return 'Substituted content';
      }),
    } as unknown as PromptTemplateLoader;
    return loader;
  }

  // Mock data loader registry
  function createMockLoaderRegistry(): ChapterDataLoaderRegistry {
    const registry = {
      loadChapterData: vi.fn(async () => ({
        variables: { project_name: 'Test Project', brand: 'Test Brand' },
        missingFields: [],
      })),
    } as unknown as ChapterDataLoaderRegistry;
    return registry;
  }

  // Mock Prisma client
  function createMockPrisma() {
    return {
      reviewConfig: {
        update: vi.fn(async () => ({})),
      },
      reportVersion: {
        findFirst: vi.fn(async () => null),
        create: vi.fn(async () => ({ id: 'version-123', versionNumber: 1 })),
      },
    } as any;
  }

  it('should produce a complete 10-chapter report even when a chapter LLM call fails', async () => {
    await fc.assert(
      fc.asyncProperty(
        // Generate a random chapter number between 2-9 (LLM chapters) that will fail
        fc.integer({ min: 2, max: 9 }),
        async (failingChapter) => {
          const templateLoader = createMockTemplateLoader();
          const loaderRegistry = createMockLoaderRegistry();
          const mockPrisma = createMockPrisma();

          // Create LLM client that fails for the specified chapter
          let callCount = 0;
          const llmClient: LLMClient = {
            chat: vi.fn(async () => {
              callCount++;
              // Chapters 2-9 call LLM. The Nth LLM call corresponds to chapter N
              // (since ch1 and ch10 are static and don't call LLM).
              // We track which chapter is being generated by the call order.
              // Calls are made in order: ch2, ch3, ..., ch9 (8 calls total)
              const currentChapter = callCount + 1; // callCount 1 = ch2, 2 = ch3, etc.
              if (currentChapter === failingChapter) {
                throw new Error(`LLM timeout for chapter ${failingChapter}`);
              }
              return `Generated content for chapter ${currentChapter}.\n\nThis is a paragraph.`;
            }),
          };

          const orchestrator = new ReportPipelineOrchestrator(
            loaderRegistry,
            templateLoader,
            llmClient,
            mockPrisma,
          );

          const result = await orchestrator.generateFullReport({
            projectId: 'project-1',
            reviewConfigId: 'review-config-1',
          });

          // The pipeline should produce exactly 10 chapters
          expect(result.chapters).toHaveLength(10);

          // The failing chapter should have status 'error' with fallback content
          const failedChapter = result.chapters[failingChapter - 1];
          expect(failedChapter.status).toBe('error');
          expect(failedChapter.content).toBe(chapterMetadata[failingChapter - 1].fallback);
          expect(failedChapter.chapterNumber).toBe(failingChapter);

          // All other chapters should have status 'generated'
          for (let i = 0; i < 10; i++) {
            if (i !== failingChapter - 1) {
              expect(result.chapters[i].status).toBe('generated');
              expect(result.chapters[i].chapterNumber).toBe(i + 1);
              // Content should not be the fallback text
              expect(result.chapters[i].content).not.toBe(chapterMetadata[i].fallback);
            }
          }
        }
      ),
      { numRuns: 20 }
    );
  });

  it('should use fallback_text from template metadata when LLM fails', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 2, max: 9 }),
        async (failingChapter) => {
          const templateLoader = createMockTemplateLoader();
          const loaderRegistry = createMockLoaderRegistry();
          const mockPrisma = createMockPrisma();

          let callCount = 0;
          const llmClient: LLMClient = {
            chat: vi.fn(async () => {
              callCount++;
              const currentChapter = callCount + 1;
              if (currentChapter === failingChapter) {
                throw new Error('Connection timeout');
              }
              return `Content for chapter ${currentChapter}.\n\nAnother paragraph.`;
            }),
          };

          const orchestrator = new ReportPipelineOrchestrator(
            loaderRegistry,
            templateLoader,
            llmClient,
            mockPrisma,
          );

          const result = await orchestrator.generateFullReport({
            projectId: 'project-1',
            reviewConfigId: 'review-config-1',
          });

          const failedResult = result.chapters[failingChapter - 1];
          const expectedFallback = chapterMetadata[failingChapter - 1].fallback;

          expect(failedResult.content).toBe(expectedFallback);
          expect(failedResult.errorMessage).toBeDefined();
          expect(failedResult.errorMessage!.length).toBeGreaterThan(0);
        }
      ),
      { numRuns: 20 }
    );
  });

  it('should not affect other chapters when one chapter fails', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 2, max: 9 }),
        async (failingChapter) => {
          const templateLoader = createMockTemplateLoader();
          const loaderRegistry = createMockLoaderRegistry();
          const mockPrisma = createMockPrisma();

          // Track which chapters were successfully generated
          const generatedChapters: number[] = [];
          let callCount = 0;

          const llmClient: LLMClient = {
            chat: vi.fn(async () => {
              callCount++;
              const currentChapter = callCount + 1;
              if (currentChapter === failingChapter) {
                throw new Error('Timeout');
              }
              generatedChapters.push(currentChapter);
              return `Unique content for chapter ${currentChapter}.\n\nParagraph two.`;
            }),
          };

          const orchestrator = new ReportPipelineOrchestrator(
            loaderRegistry,
            templateLoader,
            llmClient,
            mockPrisma,
          );

          const result = await orchestrator.generateFullReport({
            projectId: 'project-1',
            reviewConfigId: 'review-config-1',
          });

          // All LLM chapters except the failing one should have been generated
          const expectedLLMChapters = [2, 3, 4, 5, 6, 7, 8, 9].filter(
            (n) => n !== failingChapter
          );
          expect(generatedChapters.sort()).toEqual(expectedLLMChapters.sort());

          // Static chapters (1, 10) should always be generated
          expect(result.chapters[0].status).toBe('generated');
          expect(result.chapters[9].status).toBe('generated');
        }
      ),
      { numRuns: 20 }
    );
  });
});
